name = "filesystem"
description = "Platform independent, object-oriented Fortran filesystem path manipulation library. Based on C++17 filesystem."
categories = "io"
version = "3.0.0"

[install]
library = true

[library]
build-script="src/Makefile"

[build]
auto-tests = false
link="stdc++"

[[ test ]]
name="core"
source-dir = "tests"
main="test_filesystem.f90"
