name = "ffilesystem"
description = "Lightweight filesystem and path manipulations"
categories = "io"
version = "5.5.3"

[install]
library = true

[library]
source-dir = "src/common"
include-dir = ["include"]
