name = "filesystem"
description = "Lightweight filesystem and path manipulations"
categories = "io"
version = "3.9.0"

[build]
auto-tests = false

[install]
library = true


[library]
source-dir = "src/fallback"


[[test]]
name = "core"
main = "fortran/test_core.f90"
