name = "ffilesystem"
description = "Lightweight filesystem and path manipulations"
categories = "io"
version = "4.0.0"

[build]
auto-tests = false

[install]
library = true


[library]
source-dir = "src/c"
include-dir = ["include", "src/c"]


[[test]]
name = "core"
main = "fortran/test_core.f90"
