name = "fortran-pathlib"
description = "Platform independent, object-oriented Fortran filesystem path manipulation library. Based on C++17 filesystem."
categories = "io"
version = "3.0.0"

[library]
source-dir = "src"

[test]
source-dir = "src/tests"
