name: "build-test-install-example"

runs:

  using: "composite"

  steps:

  - name: install Ninja (Linux)
    if: runner.os == 'Linux'
    shell: bash
    run: |
      sudo apt update
      sudo apt install --no-install-recommends ninja-build

  - name: install Ninja (macOS)
    if: runner.os == 'macOS'
    shell: bash
    run: brew install ninja

  - name: config cpp=${{ matrix.cpp }} shared=${{ matrix.shared }}
    shell: bash
    run: >-
      cmake --preset multi
      -Dffilesystem_cpp:BOOL=${{ matrix.cpp }}
      -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}
      -DCMAKE_CXX_STANDARD=${{ matrix.cpp-std }}

  - name: log if fail
    shell: bash
    if: failure()
    run: cat build/CMakeFiles/CMakeConfigureLog.yaml

  - name: Debug workflow
    shell: bash
    run: cmake --workflow --preset debug

  - name: Release workflow
    shell: bash
    run: cmake --workflow --preset release

  - name: install package
    shell: bash
    run: cmake --install build

  - name: example workflow
    shell: bash
    run: cmake -S example -B example/build

  - run: cmake --build example/build
    shell: bash

  - run: ctest --test-dir example/build -V
    shell: bash
