name: ci

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  CTEST_NO_TESTS_ACTION: error

on:
  push:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.f90"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci.yml"
      - "!concepts/**"


jobs:

  linux-gcc:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        gcc-version: [9, 10, 11, 12]
        shared: [true, false]
        cpp: [true, false]
        exclude:
        - cpp: false
          shared: true

    env:
      CC: gcc-${{ matrix.gcc-version }}
      CXX: g++-${{ matrix.gcc-version }}
      FC: gfortran-${{ matrix.gcc-version }}

    steps:

    - name: install compilers
      run: |
        sudo apt update
        sudo apt install --no-install-recommends ninja-build

    - uses: actions/checkout@v4

    - name: config cpp=${{ matrix.cpp }} shared=${{ matrix.shared }}
      run: >-
        cmake
        --preset multi
        --install-prefix=${{ runner.temp }}
        -Dfallback:BOOL=off
        -Dcpp:BOOL=${{ matrix.cpp }}
        -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}

    - name: log if fail
      if: failure()
      run: cat build/CMakeFiles/CMakeConfigureLog.yaml

    - name: Debug workflow
      run: cmake --workflow --preset debug

    - name: Release workflow
      run: cmake --workflow --preset release

    - name: install package
      run: cmake --install build

    - name: example workflow
      run: cmake --workflow --preset default
      working-directory: example
      env:
        CMAKE_PREFIX_PATH: ${{ runner.temp }}

  old-gcc:
    needs: linux-gcc
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    strategy:
      matrix:
        gcc-version: [8]
        shared: [false]
        cpp: [true, false]

    env:
      CC: gcc-${{ matrix.gcc-version }}
      CXX: g++-${{ matrix.gcc-version }}
      FC: gfortran-${{ matrix.gcc-version }}

    steps:

    - name: install compilers
      run: |
        sudo apt update
        sudo apt install --no-install-recommends ninja-build ${{ env.CC }} ${{ env.CXX }} ${{ env.FC }}

    - uses: actions/checkout@v4

    - name: config cpp=${{ matrix.cpp }} shared=${{ matrix.shared }}
      run: >-
        cmake
        --preset multi
        --install-prefix=${{ runner.temp }}
        -Dfallback:BOOL=off
        -Dcpp:BOOL=${{ matrix.cpp }}
        -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}

    - name: log if fail
      if: failure()
      run: cat build/CMakeFiles/CMakeConfigureLog.yaml

    - name: Debug workflow
      run: cmake --workflow --preset debug

    - name: Release workflow
      run: cmake --workflow --preset release

    - name: install package
      run: cmake --install build

    - name: example workflow
      run: cmake --workflow --preset default
      working-directory: example
      env:
        CMAKE_PREFIX_PATH: ${{ runner.temp }}


  linux-clang:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        clang-version: [13, 14, 15]
        shared: [true, false]
        cpp: [true, false]
        exclude:
        - cpp: false
          shared: true

    env:
      CC: clang-${{ matrix.clang-version }}
      CXX: clang++-${{ matrix.clang-version }}
      FC: gfortran

    steps:

    - name: install compilers
      run: |
        sudo apt update
        sudo apt install --no-install-recommends ninja-build

    - uses: actions/checkout@v4

    - name: config cpp=${{ matrix.cpp }} shared=${{ matrix.shared }}
      run: >-
        cmake
        --preset multi
        --install-prefix ${{ runner.temp }}
        -Dfallback:BOOL=off
        -Dcpp:BOOL=${{ matrix.cpp }}
        -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}

    - name: log if fail
      if: failure()
      run: cat build/CMakeFiles/CMakeConfigureLog.yaml

    - name: Debug workflow
      run: cmake --workflow --preset debug

    - name: Release workflow
      run: cmake --workflow --preset release

    - name: install package
      run: cmake --install build

    - name: example workflow
      run: cmake --workflow --preset default
      working-directory: example
      env:
        CMAKE_PREFIX_PATH: ${{ runner.temp }}


  valgrind-memory:
    runs-on: ubuntu-latest
    needs: linux-gcc
    timeout-minutes: 10

    strategy:
      matrix:
        cpp: [true, false]

    steps:
    - name: install valgrind
      run: |
        sudo apt update
        sudo apt install --no-install-recommends valgrind

    - uses: actions/checkout@v4

    - run: ctest -Dopts="-Dcpp:BOOL=${{ matrix.cpp }} -Dfallback:BOOL=off" -S memcheck.cmake -V

    - name: upload Valgrind log
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: valgrind-log
        path: build-Valgrind/Testing/Temporary/MemoryChecker.*.log

  clang-tidy:
    runs-on: ubuntu-latest
    needs: linux-gcc
    timeout-minutes: 10

    strategy:
      matrix:
        cpp: [false]
    # it seems clang-tidy 14 can't handle std::filesystem?

    steps:
    - uses: actions/checkout@v4

    - run: cmake --preset tidy -Dcpp:BOOL=${{ matrix.cpp }} -Dfallback:BOOL=off
    - run: cmake --build --preset tidy

# disabled coverage due to broken Jinja import
  # linux-coverage:
  #   runs-on: ubuntu-latest
  #   needs: linux-gcc
  #   timeout-minutes: 10

  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: actions/setup-python@v2
  #     with:
  #       python-version: '3.9'

  #   - name: install Gcovr
  #     run: pip install gcovr

  #   - run: cmake --preset coverage
  #   - run: cmake --build --preset coverage

  #   - name: Code coverage
  #     run: cmake --build --preset run-coverage

  #   - uses: actions/upload-artifact@v2
  #     with:
  #       name: coverage-report-html
  #       path: build-coverage/coverage/


  mac:
    runs-on: macos-latest
    needs: linux-clang
    timeout-minutes: 10

    strategy:
      matrix:
        compiler: [ {cpp: g++-12, c: gcc-12}, {cpp: clang++, c: clang} ]
        shared: [false]
        cpp: [true, false]
        include:
        - shared: true
          cpp: true
          compiler: {cpp: clang++, c: clang}

    env:
      CC: ${{ matrix.compiler.c }}
      CXX: ${{ matrix.compiler.cpp }}
      FC: gfortran-12

    steps:

    - run: brew install ninja

    - uses: actions/checkout@v4

    - name: config cpp=${{ matrix.cpp }} shared=${{ matrix.shared }}
      run: >-
        cmake
        --preset multi
        --install-prefix=${{ runner.temp }}
        -Dfallback:BOOL=off
        -Dcpp:BOOL=${{ matrix.cpp }}
        -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}

    - name: log if fail
      if: failure()
      run: cat build/CMakeFiles/CMakeConfigureLog.yaml

    - name: Debug workflow
      run: cmake --workflow --preset debug

    - name: Release workflow
      run: cmake --workflow --preset release

    - name: install package
      run: cmake --install build

    - name: example workflow
      run: cmake --workflow --preset default
      working-directory: example
      env:
        CMAKE_PREFIX_PATH: ${{ runner.temp }}
