name: ci_cmake

on:
  push:
    paths:
      - "**/*.f90"
      - "**/CMakeLists.txt"
      - "**/*.cmake"
      - ".github/workflows/ci_cmake.yml"


jobs:

  linux-gcc:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        gcc-version: [7, 8, 9, 10, 11]

    env:
      CC: gcc-${{ matrix.gcc-version }}
      CXX: g++-${{ matrix.gcc-version }}
      FC: gfortran-${{ matrix.gcc-version }}

    steps:
    - uses: actions/checkout@v2

    - name: install ninja and compilers
      run: |
        sudo apt update
        sudo apt install ninja-build gcc-${{ matrix.gcc-version }} g++-${{ matrix.gcc-version }} gfortran-${{ matrix.gcc-version }}

    - run: cmake --preset multi

    - run: cmake --build --preset debug
    - run: ctest --preset debug -V

    - run: cmake --build --preset release
    - run: ctest --preset release -V


  linux-clang:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        clang-version: ["6.0", 7, 8, 9, 10]

    env:
      CC: clang-${{ matrix.clang-version }}
      CXX: clang++-${{ matrix.clang-version }}
      FC: gfortran

    steps:
    - uses: actions/checkout@v2

    - name: install ninja and compilers
      run: |
        sudo apt update
        sudo apt install ninja-build clang-${{ matrix.clang-version }}

    - run: cmake --preset multi

    - run: cmake --build --preset debug
    - run: ctest --preset debug -V

    - run: cmake --build --preset release
    - run: ctest --preset release -V


  valgrind-memory:
    runs-on: ubuntu-latest
    needs: linux-gcc
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: install valgrind
      run: |
        sudo apt update
        sudo apt install valgrind

    - run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug
    - run: cmake --build build

    - name: Memory leak check
      run: ctest -T memcheck --test-dir build -V


  linux-coverage:
    runs-on: ubuntu-latest
    needs: linux-gcc
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: install Gcovr
      run: pip install gcovr

    - run: cmake --preset coverage
    - run: cmake --build --preset coverage

    - name: Code coverage
      run: cmake --build --preset run-coverage

    - uses: actions/upload-artifact@v2
      with:
        name: coverage-report-html
        path: build-coverage/coverage/


  mac:
    runs-on: macos-latest
    needs: linux-clang
    timeout-minutes: 10

    strategy:
      matrix:
        compiler: [ {cpp: g++-11, c: gcc-11}, {cpp: clang++, c: clang} ]

    env:
      FC: gfortran-11
      CC: ${{ matrix.compiler.c }}
      CXX: ${{ matrix.compiler.cpp }}

    steps:
    - uses: actions/checkout@v2

    - run: brew install ninja

    - run: cmake --preset multi

    - run: cmake --build --preset debug
    - run: ctest --preset debug -V

    - run: cmake --build --preset release
    - run: ctest --preset release -V


  windows:
    runs-on: windows-latest
    needs: linux-gcc
    timeout-minutes: 10

    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc-fortran

    - uses: actions/checkout@v2

    - run: cmake --preset multi

    - run: cmake --build --preset debug
    - run: ctest --preset debug --schedule-random -V

    - run: cmake --build --preset release
    - run: ctest --preset release --schedule-random -V
