name: ci_cmake

on:
  push:
    paths:
      - "**/*.f90"
      - "**/CMakeLists.txt"
      - "**/*.cmake"
      - ".github/workflows/ci_cmake.yml"


jobs:

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2

    - name: install ninja
      run: |
        sudo apt update
        sudo apt install ninja-build

    - run: cmake --preset multi

    - run: cmake --build --preset debug
    - run: ctest --preset debug -V

    - run: cmake --build --preset release
    - run: ctest --preset release -V


  linux-coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: install Gcovr
      run: pip install gcovr

    - run: cmake --preset coverage
    - run: cmake --build --preset coverage

    - name: Code coverage
      run: cmake --build --preset run-coverage

    - uses: actions/upload-artifact@v2
      with:
        name: coverage-report-html
        path: build-coverage/coverage/


  mac:
    runs-on: macos-latest
    timeout-minutes: 10

    env:
      FC: gfortran-11

    steps:
    - uses: actions/checkout@v2

    - run: brew install ninja

    - run: cmake --preset multi

    - run: cmake --build --preset debug
    - run: ctest --preset debug -V

    - run: cmake --build --preset release
    - run: ctest --preset release -V


  windows:
    runs-on: windows-latest
    timeout-minutes: 10

    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc-fortran

    - uses: actions/checkout@v2

    - run: cmake --preset multi

    - run: cmake --build --preset debug
    - run: ctest --preset debug --schedule-random -V

    - run: cmake --build --preset release
    - run: ctest --preset release --schedule-random -V
