name: ci_cmake

env:
  CMAKE_GENERATOR: Ninja

on:
  push:
    paths:
      - "**/*.f90"
      - "**/CMakeLists.txt"
      - "**/*.cmake"
      - ".github/workflows/ci_cmake.yml"


jobs:

  linux-win:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      # just for Ninja
      with:
        python-version: 3.x

    - run: pip install ninja

    - run: cmake --preset multi

    - run: cmake --build --preset debug
    - run: ctest --preset debug -V

    - run: cmake --build --preset release
    - run: ctest --preset release -V


  linux-coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: install Gcovr
      run: pip install gcovr ninja

    - run: cmake --preset coverage
    - run: cmake --build --preset coverage

    - name: Code coverage
      run: cmake --build --preset run-coverage

    - uses: actions/upload-artifact@v2
      with:
        name: coverage-report-html
        path: build-coverage/coverage/

  mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    env:
      FC: gfortran-11

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      # just for Ninja
      with:
        python-version: 3.x

    - run: pip install ninja

    - run: cmake --preset multi

    - run: cmake --build --preset debug
    - run: ctest --preset debug -V

    - run: cmake --build --preset release
    - run: ctest --preset release -V
