name: ci_meson

on:
  push:
    paths:
      - "**/meson.build"
      - ".github/workflows/ci_meson.yml"

jobs:

  linux-gcc:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - run: pip install meson ninja

    - run: meson setup build
    - run: meson compile -C build

    - run: meson test -C build -v
